# This file defines the parameters of the xARM
# Please use an ethernet cable and connect the robot to intranet via LAN
# According to the documentation, the IP should be in the following range:
---
host: '192.168.254.97'
port: 18333
Tcp_Speed: 100,
Tcp_Acc: 2000,
Angle_Speed: 20,
Angle_Acc: 500
